Add support for tls
tremor-rs/tremor-runtime pull request #1055
Opened 2021-05-22 18:21 UTC by murex971

Signed-off-by: murex971 <nupur202000@gmail.com>

# Pull request

## Description

add support for receiving TLS encrypted data via TCP onramp

## Related

* Related Issues: fixes #12 (Phase 3)

## Checklist

* [X] The RFC, if required, has been submitted and approved
* [ ] Any user-facing impact of the changes is reflected in docs.tremor.rs
* [ ] The code is tested
* [X] Use of unsafe code is reasoned about in a comment
* [ ] Update CHANGELOG.md appropriately, recording any changes, bug fixes, or other observable changes in behavior
* [ ] The performance impact of the change is measured (see below)

## Performance

2021-05-22 19:39 UTC, Licenser commented on src/source/tcp.rs
> +                    .and_then(|tls_config| load_server_config(tls_config).ok())
we should fail when the certificates can't be loaded not silently switch to non SSL mode. That could be quite confusing for operators and be quite a security issue.

2021-05-22 19:48 UTC, Licenser requested changes
Other than the cert loading and a missing stream end this looks great :D! Some nice refactoring of the read_loop and I quite like how good the errors are for the certs!

2021-05-22 19:48 UTC, Licenser commented on src/source/tcp.rs
> +                                error!("TLS Error: {}", e);
Since stream start was send above we would need to send a stream end here

2021-05-25 10:28 UTC, mfelsche approved these changes

2021-05-25 10:29 UTC, mfelsche commented on src/source/tcp.rs
> +                            Err(e) => {
Dang, this `e` is not used.
```suggestion
                            Err(_e) => {
```

2021-05-25 16:34 UTC, Licenser approved these changes
woooh nice!

2021-05-25 16:41 UTC, mfelsche approved these changes

2021-05-25 16:41 UTC, merged