Fixing broken links described in issue#2701
tremor-rs/tremor-runtime pull request #2702
Opened 2024-12-21 12:35 UTC by devskillz47

# Pull request
Fix "broken" links included in the Issue#2701(https://github.com/tremor-rs/tremor-runtime/issues/2701)

2025-01-06 14:13 UTC, Licenser requested changes
Can we link this to edge instead of 0.12:

1) edge will not go out of date as a long
2) edge effects what is directly in github so it is the more correct link I think

2025-01-06 19:47 UTC, devskillz47 commented
will do, but took a little break for the holidays... :p

2025-01-07 13:26 UTC, Licenser commented
All good, I just wanted to track it  before I forget :)

2025-01-13 17:24 UTC, devskillz47 commented
so, i had a more in depth look at this. it seems that currently everything points to v0.12. my only concern in moving it to edge would be that if in the installation instructions we point to the latest release (in this case v0.12) and in the documentation we point it to edge the features described in the documentation might not be there for the users who followed the instructions which could be quite cumbersome.

2025-01-22 08:31 UTC, Licenser commented
That's a fair point, then lets just make sure we update the version in the README as we release!

2025-01-22 08:31 UTC, Licenser approved these changes

2025-01-22 08:31 UTC, merged